# apiVersion: v1
# kind: Secret
# metadata:
#   name: <NAME OF THE Secret>
# type: Opaque
# data:
#   <THE KEY FROM Secret WHICH has THE ENCODED PASSWORD>: <OUTPUT OF `echo -n 'the password' | base64`>

apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-configmap
data:
  DB_USERNAME: "myuser"
  DB_NAME: "mydatabase"
  DB_HOST: "postgresql-service.default.svc.cluster.local"
  DB_PORT: "5432"